SELECT distinct ?item
WHERE
{
  VALUES ?goodRanks { wikibase:NormalRank wikibase:PreferredRank }
  ?item p:P2397 ?yt.
  ?yt wikibase:rank ?goodRanks.

  FILTER NOT EXISTS {?itemO ontolex:sense ?item}.
  FILTER (!(contains(str(?item), "L" ))).

  ?article schema:about ?item .
  ?article schema:isPartOf <https://en.wikipedia.org/>.
} 
