SELECT distinct ?item
WHERE
{
  VALUES ?goodRanks { wikibase:NormalRank wikibase:PreferredRank }
  ?item p:P2397 ?yt.
  ?yt wikibase:rank ?goodRanks.

  ?item wikibase:sitelinks [].

  ?article schema:about ?item .
  ?article schema:isPartOf <https://en.wikipedia.org/>.
} 
