SELECT distinct ?item
WHERE
{
  VALUES ?goodRanks { wikibase:NormalRank wikibase:PreferredRank }
  ?item p:P2002 ?twt.
  ?twt wikibase:rank ?goodRanks.

  FILTER EXISTS { ?twt pq:P585 ?pointTime. }
  FILTER EXISTS { ?twt pq:P3744 ?f. }
  FILTER EXISTS { ?twt pq:P6552 ?id. }
}