---
# Run borkedbot on kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borkedbot.bot
  namespace: tool-borkedbot
  labels:
    name: borkedbot.bot
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: borkedbot.bot
      toolforge: tool
  template:
    metadata:
      labels:
        name: borkedbot.bot
        toolforge: tool
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/borkedbot/bin/borkedbot.sh", "run" ]
          workingDir: /data/project/borkedbot
          env:
            - name: HOME
              value: /data/project/borkedbot
          imagePullPolicy: Always

