---
# Run borkedbot prefer-dates job on kubernetes
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: borkedbot.bot-prefer-dates
  namespace: tool-borkedbot
  labels:
    name: borkedbot.bot-prefer-dates
    toolforge: tool
spec:
  schedule: "4 0 * * 5" # weekly on thurs
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: borkedbot.bot-prefer-dates
            toolforge: tool
        spec:
          activeDeadlineSeconds: 604800
          restartPolicy: OnFailure      
          containers:
            - name: bot
              image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
              command: [ "/data/project/borkedbot/borked-bot/bin/borkedbot.sh", "run-prefer-dates" ]
              workingDir: /data/project/borkedbot
              env:
                - name: HOME
                  value: /data/project/borkedbot
              imagePullPolicy: Always

