---
# Run borkedbot yt job on kubernetes
apiVersion: batch/v1beta
kind: Job
metadata:
  name: borkedbot.bot-yt
  namespace: tool-borkedbot
  labels:
    name: borkedbot.bot-yt
    toolforge: tool
spec:
  schedule: "@weekly"
  concurrencyPolicy: Forbid
  ttlSecondsAfterFinished: 60  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: borkedbot.bot-yt
            toolforge: tool
        spec:
          activeDeadlineSeconds: 604800
          restartPolicy: OnFailure      
          containers:
            - name: bot
              image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
              command: [ "/data/project/borkedbot/borked-bot/bin/borkedbot.sh", "run-yt" ]
              workingDir: /data/project/borkedbot
              env:
                - name: HOME
                  value: /data/project/borkedbot
              imagePullPolicy: Always

