---
# Run borkedbot yt job on kubernetes
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: borkedbot.bot-yt-vid
  namespace: tool-borkedbot
  labels:
    name: borkedbot.bot-yt-vid
    toolforge: tool
spec:
  schedule: "0 0 * * 3" # weekly on tues
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: borkedbot.bot-yt-vid
            toolforge: tool
        spec:
          activeDeadlineSeconds: 604800
          restartPolicy: OnFailure      
          containers:
            - name: bot
              image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
              command: [ "/data/project/borkedbot/borked-bot/bin/borkedbot.sh", "run-yt-vid" ]
              workingDir: /data/project/borkedbot
              env:
                - name: HOME
                  value: /data/project/borkedbot
              imagePullPolicy: Always

