SELECT distinct ?item
WHERE
{
  VALUES ?goodRanks { wikibase:NormalRank wikibase:PreferredRank }
  ?item p:P6262 ?f.
  ?f wikibase:rank ?goodRanks.
  # don't look at dead pages or already tagged ones
  FILTER NOT EXISTS { ?f pq:P582 ?endTime. }
  FILTER NOT EXISTS { ?f pq:P1534 ?endCause. }
  FILTER NOT EXISTS {?f pq:P407 ?fLang. }

}
