SELECT distinct ?item
WHERE
{
  VALUES ?goodRanks { wikibase:NormalRank wikibase:PreferredRank }
  ?item p:P2002 ?twt.
  ?twt wikibase:rank ?goodRanks.
  # don't look at dead accounts
  FILTER NOT EXISTS { ?twt pq:P582 ?endTime. }
  FILTER NOT EXISTS { ?twt pq:P1534 ?endCause. }

  FILTER NOT EXISTS { ?item wdt:P8687 ?followers. }

  ?twt pq:P6552 ?twId.
  FILTER (!isBlank(?twId)).

}